### ISSUE TITLE
Vue Toastification supports composition API

### ISSUE THREAD

**Issue by Maronato** [sabifa/ESP-Weatherstation#1]
Hello!
I noticed that you are using composition API on your repo and I want to let you know that the newest [release](https://github.com/Maronato/vue-toastification/releases/tag/v1.6.0) of Vue Toastification introduces support for it. You can check the docs [here](https://github.com/Maronato/vue-toastification#composition-api-registration).

By using the new release you avoid having to do stuff like:
https://github.com/sabifa/ESP-Weatherstation/blob/1bb04581b49b855f2c2986a39baed10d8a582bc3/weatherstation_frontend/src/views/Login.vue#L41

Don't hesitate to report any issues you find.

**Comment by sabifa** [comment]
Thanks for the hint!
The docs look promising, I will take a look at it in the next days :slightly_smiling_face:
